version: "3.9"

services:
  db:
    image: postgres:14
    container_name: fastapi_starter-db
    # env_file:
    #   - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "${POSTGRES_DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: fastapi_starter-app
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi_starter-pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
